[package]
name = "tsubasa"
version = "0.1.0"
cairo-version = "2.1.0"

[cairo]
sierra-replace-ids = true

[dependencies]
dojo = { git = "https://github.com/dojoengine/dojo" , rev = "bec0ca26233018c1a1a62d038320567e38b1461c"}

[[target.dojo]]

[tool.dojo.env]
rpc_url = "http://localhost:5050/"
# Default account for katana with seed = 0
account_address = "0x03ee9e18edc71a6df30ac3aca2e0b02a198fbce19b7480a63a0d71cbd76652e0"
private_key = "0x0300001800000000300000180000000000030000000000003006001800006600"
# world_address = "0x591ca912b1f5d90b35224af1fe8d9aca9a54dd6470042009623d78d8a9ef0fc"
